### ISSUE TITLE
Laser for interacting break's frequently

### ISSUE THREAD

**Issue by Ardescar** [Frooxius/NeosPublic#1706]
## Describe the bug

This is about a "Laserbug" - something appears to prevent the laser in neos from working and causes other issues too. 

In Neos the laser for interacting with the UI does start to flicker sometimes and is then 99% not usable for interaction with the user interfaces anymore. It respawns the user "randomly".

When this happens - The IK is breaking - the locomotion is breaking.
Solution is - if that happens - only a neos restart.   
So far i only know about 2 people in neos that have the bug. 
I have collected Videos and logfiles from Atomicwave and CyberZott.

## Relevant issues

There is no other open issue that does have the same content. 

## To Reproduce

This is not able to be reproduced so far - i didnt find a way.

__when__ 
- sometimes it happens after login  
- sometimes after a while in a world
- or right after being afk
- but sometimes it takes days to happen
__where__ 
- in every world - no mather if full or gridspace or homeworld
__who__
- it happens in any avatar (robot,avali,protogen) and no matter if ppl around or alone
- it also happens to a fresh created account on the same neos installation 
- but also happens on a fresh reinstalled neos - with removing every known bit of neos left in the system 
- also with reset laser settings 

We did run out of things to try.

## Hardware 

CyberZott's PC
CPU: Intel Core i7-7700
GPU: nVidia GeForce GTX 1660 Super
RAM: Corsair Vengeance LPX 16 GB (2 x 8 GB) DDR4 2400 MHz
VR Headset: Oculus Rift CV1 - Native Oculus Neos VR build(edited)

atomicwave's PC
CPU: Intel Core i7-8700K
GPU: nVidia GeForce GTX 1080
RAM: 16 GB (2 x 8 GB) DDR4 2400 MHz
VR Headset: HTC Vive - SteamVR Neos VR build

## Video / Logfiles

How does it look like for other ppl -> https://www.strzl.de/video/2021-01-12-laserbug.mp4

Several videos from Cyber's perspective over the past weeks -> about 6 mins - to show the bug 
and the maybe correlated issues -> https://youtu.be/yl_38V1sg68      (logfiles from the videos in the zip file)

I have collected allot logfiles and uploaded them. -> https://strzl.de/upload/laserbug-log-files.zip

## Bug information:
 - How often does it happen: Sometimes ... every 2 to 4 Days - but sometimes twice a day.  
 - Does the bug persist after restarting Neos? No. 
 - Neos Version: All versions in the past ~ half year!?
 - Neos Platform: Windows 10 - different builds.

## Additional context

Sometimes it breaks locomotions and/or ik when its happening. (breaks = its not working or behaving strange)
The laser flickering bug sometimes rarely seems to go away for some moments to let you klick somewhere...
It is there since at least early Summer 2020.
 
A complete reinstall of neos didnt help - even with cleaning cache and assets and registry.
Also installing neos to a different drive didnt help. 

The laser settings have been reset several times. 

## Person's that have the bug: 
CyberZott  -  CyberZott#5567         (Bug happens average every 2 Days) 
Atomicwave -  EvawdnousCimota#2730   (Bug happens average every 4 Days) 

## Reporter: 
Ardes - Ardescar#2046

## Additional description from CyberZott - Laserbug issues:

__These things always happen:
I will randomly respawn.
Opening the context menu on one hand, then the other can also result in a respawn.
I will no longer be able to move around using physical locomotion, even if I can select it. I just won’t be able to move.

__Other things I’ve noticed but that don’t always happen:
I will notice avatars very quickly moving back to spawn and then back to the user. This usually happens so quickly that it looks like they flash.
IK will usually break for other users. Things like feet moving up to the shoulders or avatars leaning when they shouldn’t be.
I will get kicked back to my local home with the “World Crashed” error even though the session is still working for others.
Sometimes the laser will start to work again but sometimes I will only be able to click the last item on the dash. 
To explain further, the bottom of the dash will only highlight the close button and the top of the dash will highlight the last option available such as the “send voicemail” option in the contact’s screen. 
The lasers “recovering” is usually temporary and they will break again.
The online contact notification will be darker as if it is highlighted and my lasers will flicker even if I don’t have them active.

**Comment by Ardescar** [comment]
Also with the current Neos-Version the Bug is still existing - LogFile from Today - from Atomicwave.
[HOME_-_2021.2.3.616_-_2021-02-03_17_13_09.log](https://github.com/Frooxius/NeosPublic/files/5920420/HOME_-_2021.2.3.616_-_2021-02-03_17_13_09.log)

**Comment by Frooxius** [comment]
Thanks for the info. It seems like there is something corrupted in the environment, particularly a collider, that's feeding NaN's into the system. I've added guards to prevent that from breaking the lasers in the next build, but you might want to check if there's anything in the world that might be triggering this.

E.g. does this happen only in particular world? Or when particular items are around? If you could find in which world it happens or which items triggers it, could you send it to me for testing so I can better isolate where it's coming from?

**Comment by Frooxius** [comment]
I've pushed some fixed in 2021.2.7.1345. It doesn't likely fix the underlying issues though, but can you check if it makes any difference please?

**Comment by Ardescar** [comment]
Yes we will look into it if this is changing anything.
And we still trying to find the chause. But so far - there is no special world or avatar or item involved. 
I tried allot to reproduce it on my system.
Thank you.

**Comment by shiftyscales** [comment]
Hey @Frooxius - I believe I've identified a potential source of this issue with a report from Espa#1302.

If I take off my headset, the laser will stop responding to clicks on interfaces, etc.

What was happening in Espa's case, their headset (G2) was momentarily being disconnected due to USB issues which would reset the state of the presence sensor. It would think they weren't in the headset.

I think that might potentially be what's happening in the case of the other users too.

**Comment by Ardescar** [comment]
With the past patch the laser is not flickering that much anymore ...
... but its still breaking at some point. And it still gets the NAN feed into.

I was wondering if this is a result of timing and/or hardware inputs from different hardware setups.  

## Descriptions of what happened after Patch
--
Atomicwave did have a respawn and a breaking locomotion. (physical locomotion is not working - while fly or noclip is)
This was earlier always in correlation with "Laser Bug" and also with breaking dash.
--
Cyberzott did got kicked out of a world while being afk - neos said  "the world crashed" but the world was still running.
(this was also often the same time happening while/with the "laser bug") 
It also did break the dash again.

## Additional 

"**Breaking Dash**" means that only the last button in dash-bar or dash-window can be clicked. and its always selected.
You can't click anywhere else you always click the last button. 
So for example in the lower dash bar - Exit is always selected. 
--
We found the User Azioinferno (AzioInferno#0831) and he does have a version of that issue around every few days.
For him the main issue so far is that he sometimes does also have a breaking UI/dash and he can only press the last dash/window button. 
He joined neos a month ago - and he uses a CV1.
-- 
I personally had this breaking dash myself i guess one time in the past.
With that in mind i searched my logfiles for NaN and i found at least one time that i had one with invalid bounds in my laser.
This was 3 Months ago and i also was respawned by destroying user.

## In general

So the patch did reduce the laser flickering, but all the other things like: - respawns - world crash
- locomotion break - breaking dash
is still existing.

## Logfiles
[CyberZott - H170-PRO_-_2021.2.7.1345_-_2021-02-08_14_50_08.log](https://github.com/Frooxius/NeosPublic/files/5957094/CyberZott.-.H170-PRO_-_2021.2.7.1345_-_2021-02-08_14_50_08.log)
[Atomicwave - HOME_-_2021.2.7.1345_-_2021-02-08_14_45_11.log](https://github.com/Frooxius/NeosPublic/files/5957096/Atomicwave.-.HOME_-_2021.2.7.1345_-_2021-02-08_14_45_11.log)

**Comment by Ardescar** [comment]
Here a separate video for the dash behavior when the input is "breaking". https://www.youtube.com/watch?v=AsTi6k0rZMs
From what i can see so far there is no information in the log when the UI is behaving like this.
(its a big logfile over several hours)

**Comment by Ardescar** [comment]
Update from Cyber when the laser interaction with the dash did break again.

[H170-PRO - 2021.3.12.44 - 2021-03-14 22_46_40.log](https://github.com/Neos-Metaverse/NeosPublic/files/6184492/H170-PRO.-.2021.3.12.44.-.2021-03-14.22_46_40.log)

**Comment by Ardescar** [comment]
A logfile from Atomic - he got suddenly respawned - and was not able to move in physical locomotion and the lasers didnt work 
then fps did go down. 

[HOME_-_2021.3.16.1287_-_2021-03-22_17_06_15.log](https://github.com/Neos-Metaverse/NeosPublic/files/6184503/HOME_-_2021.3.16.1287_-_2021-03-22_17_06_15.log)

**Comment by Ardescar** [comment]
> If I take off my headset, the laser will stop responding to clicks on interfaces, etc.
>What was happening in Espa's case, their headset (G2) was momentarily being disconnected due to USB issues which would reset > the state of the presence sensor. It would think they weren't in the headset.
> I think that might potentially be what's happening in the case of the other users too.

Both - Atomic and Cyber did try to put down their Headsets - and did put them back on - but this didnt solve the issue.

**Comment by Ardescar** [comment]
Update again:
It seems to happen these days a bit more often.

Description about all wierd things inside the Video below:
Unable to grab anything with my grab spheres.
Laser appears on context menu only when moving with the analogue stick.
I could only move because I was already in noclip locomotion.
I switched to physical and couldn't move, only rotate.
I then couldn't switch back to noclip as I couldn't move with the analogue stick.
The guide laser (when you press trigger and the laser turns on) looks fine until it moves over something grabbable. When this happens the laser dissapears again.
If I grab whilst the laser is gone I actually grab the object but it pushes the object out in front of me instead of staying where it is.
Physical buttons however worked fine.
My dash would only let me pick the very last menu item.
My game then crashed. I don't recall doing anything to cause the crash.

[H170-PRO - 2021.3.25.446 - 2021-03-26 16_33_43.log](https://github.com/Neos-Metaverse/NeosPublic/files/6255610/H170-PRO.-.2021.3.25.446.-.2021-03-26.16_33_43.log)

https://strzl.de/video/2021.03.26-17.57.21.02.mp4

**Comment by Ardescar** [comment]
Here the mentioned bug with being in in desktop mode too - so the mouse did not work and like no klicking possible.
Also rotating avatar in desktop mode is not working when the laser is bugging.

https://strzl.de/video/2021.04.05-00.05.14.03.mp4

[H170-PRO - 2021.4.2.690 - 2021-04-04 19_51_59.log](https://github.com/Neos-Metaverse/NeosPublic/files/6255666/H170-PRO.-.2021.4.2.690.-.2021-04-04.19_51_59.log)

**Comment by Ardescar** [comment]
Ahoi, Just want to write a update. The bug is still existing and alife and occuring every day!

It also seems to happen sligtly more often currently and - as said - its also happening in desktop.
And it also happens if you only launch neos in screenmode without even using VR.

Here is a fresh logfile from today with some errors!!!
[H170-PRO - 2021.5.24.1203 - 2021-05-25 11_11_16.log](https://github.com/Neos-Metaverse/NeosPublic/files/6540853/H170-PRO.-.2021.5.24.1203.-.2021-05-25.11_11_16.log)

**Comment by Ardescar** [comment]
Yesterday i was attached onto one Avatar of a Player that did start to have the Bug - and it did respawn us by forcing us both into floatpoint errors. After that the Laser was broken.

**Comment by Ardescar** [comment]
Hey H3BO3
 - have you been able to interact with your context menu or with your dash?
 - have you been able to grab stuff ? 
 - if you rotate your avatar while having this bug - the laser will work again while you rotate.
 - did only the last button of your dash menu work ?

Also this bug-behaviour and the variety of things that happen is everytime a bit different - it can crash you - respawn you - or just no interaction possible - or sometimes the locomotion and the Ik of avatars is messed -  etc ... - most of the time there is not even a entry in the logfiles that tell that something did happen.

In your case and in general -> most of the time when your not able to click anything its a collider that blocks the laser.
This bug here tho ... is a riddle to me. I tried allot things to reproduce :P
 
Iam tempted to rebuild one of their pc systems to see if it happens.
