### ISSUE TITLE
Anchoring another user via Logix causes offset transforms

### ISSUE THREAD

**Issue by Hayden-da-Serg** [Frooxius/NeosPublic#1714]
## Describe the bug
Whenever a user sends an impulse to anchor another user into an avatar anchor, the transform of the anchored user is not correct and the user does not end up where the anchor should be anchoring them.

## Relevant issues
Potentially #1705 ?
## To Reproduce
- Create an Avatar Anchor that positions the anchored user to a set position
- Make some Logix so one user anchors another user
- Have one user send the impulse to anchor another user

## Expected behavior
The anchored user would be expected to positioned wherever the anchor is telling them to anchor, however if they are anchored by another user then they aren't positioned correctly.

## Screenshots / Video
![image](https://user-images.githubusercontent.com/25524760/106988758-bdc62200-672d-11eb-87dc-89dab3868e54.png)
Screenshot of the Logix setup to replicate this.
![image](https://user-images.githubusercontent.com/25524760/106988960-46dd5900-672e-11eb-916f-4f12c8b526cb.png)
Screenshot of where I was anchored when someone else anchored me (my hips should be in the middle of the sphere)
![image](https://user-images.githubusercontent.com/25524760/106989034-77bd8e00-672e-11eb-9c6e-acbbcc0a7b42.png)
Screenshot of where I was anchored whenever I anchored myself.

## Bug information (please complete the following information):
 - How often does it happen: Always
 - Does the bug persist after restarting Neos? Yes
 - Neos Version: 2021.2.4.348
 - Neos Platform: Any
 - Link to reproduction World/Item: link to object used to reproduce can be found in `Hayden Public > _temp > Offset Anchor Debug`
 Link to Hayden Public can be found here: neosrec:///U-Hayden/R-01c97f2a-5862-41bc-b27c-61bb23949236
 - Regression: Yes, Before build 2021.2.3.616 this did function as expected.

## Additional context
N/A

## Reporters:
Hayden#3180

**Comment by Frooxius** [comment]
This sounds like issue that was fixed in 2021.2.4.348. Are you sure that everyone involved in the test is on the latest build?

**Comment by Hayden-da-Serg** [comment]
Yes, both me and Lucas are on 2021.2.4.348, and we are the only two testing.

**Comment by TehTurk** [comment]
I've also witnessed this in other anchor systems too but more severe. Some other examples are the Flying Scooter from forever ago. If you scale it down and then sit, you will obliterate.

**Comment by chemicalcrux** [comment]
Ah, yes, this is probably a related issue to the one that was fixed recently. I don't think we tested any cases with one user anchoring another user *where the anchor sets your position*. The ones we happened to try were all anchors that don't change your position.

**Comment by Frooxius** [comment]
When you noticed that, was everyone also using 2021.2.4.348? Keep in mind that build is compatible with previous ones, so anyone potentially running older build could be still source of the old problem.

**Comment by shiftyscales** [comment]
> Yes, both me and Lucas are on 2021.2.4.348, and we are the only two testing.

It sounds like it this was the latest build unfortuantely, @Frooxius.

**Comment by Hayden-da-Serg** [comment]
Yes, everyone in the world was using the same build

**Comment by Hayden-da-Serg** [comment]
> I've also witnessed this in other anchor systems too but more severe. Some other examples are the Flying Scooter from forever ago. If you scale it down and then sit, you will obliterate.

I've also noticed that the more the anchor is scaled the worse the issue gets.

**Comment by Frooxius** [comment]
Ok thanks! Just making sure we're not chasing a bug that was already fixed. I'm looking into this now.

**Comment by Frooxius** [comment]
Hmm... I'm testing this, but I can't replicate it, it behaves correctly. I tried both with the host parenting guest and guest parenting host, but in both cases the offset is correct.

Are you absolutely sure when you reproduced this everyone had the correct build number? 

I've pushed a new build 2021.2.5.435 to the danger nightly channel, can you check on that one and see if you can still replicate it?

**Comment by Hayden-da-Serg** [comment]
I'm just about to get to sleep, next time I'm able to test I'll see what I can get.

**Comment by Hayden-da-Serg** [comment]
Now I'm curious if it could be related to using the `Local Space` option, all of the anchors in my testing and my use case use this option to make sure things are parented.

**Comment by Hayden-da-Serg** [comment]
Alrighty, just tested 2021.2.5.435, and the issue is still present, and my theory in the previous comment was debunked, the issue exists both whenever `LocalSpace` has a slot defined and when there isn't.
As a quick sanity check, I ran tests by running the impulses myself, and those functioned as expected, I spoofed an impulse from someone else and I asked someone else to send the impulse themselves, both cases of them sending the impulse resulted in incorrect anchor transforms.
Here's a video demonstrating that.
https://streamable.com/8f4xg2

**Comment by Hayden-da-Serg** [comment]
I updated the debugging anchors I'm using in the same link as mentioned in the `Link to reproduction World/Item` section to go between two anchors.
I've also found that the issue does not exist whenever it's performed between two users on the local network, so it seems to be highly reliant on the network delay.

**Comment by Frooxius** [comment]
I see, thanks for the info! Yeah the network delay is likely why I couldn't reproduce it on my end. I'll add some network delay and test again.

**Comment by Frooxius** [comment]
Hmm I'm still having some trouble replicating this in isolation, even with network latency (200 ms).

- Does it happen even if the user is stationary or do they need to be moving?
- Does the active locomotion type have any effect? E.g. does it happen if they're in no-clip?
- Does it affect only VR users or also users in the debug screen mode?

**Comment by Hayden-da-Serg** [comment]
These are from memory, I'll let you know when I have the chance to do further testing.
- It seems to happen no matter what their current velocity state is, in my testing I was stationary, but I've seen others break while they were moving.
- It appears to always happen no matter the locomotion mode.
- In my testing I was in screen mode, but I have also seen this happen to VR users.

**Comment by Frooxius** [comment]
Hmm that's odd. I can't really get it to happen on my end with those conditions. 

- Does it happen with any avatar? E.g. even the default headset and hands?
- Do you have any queued packets when this occurs?

**Comment by Frooxius** [comment]
Can you re-check the behavior in 2021.2.7.1345 when you get the chance please?

**Comment by Hayden-da-Serg** [comment]
I'll check as soon as I'm able to get into the build, can't at the moment due to the SteamVR thing happening.

**Comment by Hayden-da-Serg** [comment]
Nope, still offset.

**Comment by Hayden-da-Serg** [comment]
@Frooxius If you're able to at some point I'd love to get in a world to test, I'm very easily able to replicate the issue.

**Comment by Frooxius** [comment]
Ideally I need to be able to replicate this myself, so I can iterate on narrowing down the cause and finding the solution. If not, I can put instrumented builds to the #danger-nightly and you'll have to send me the logs, but that's going to be a fair bit slower.

What about my last two questions?

**Comment by Hayden-da-Serg** [comment]
From what I could tell it happens on every avatar, as for queued packets there's none that I could tell of, though considering how often it happens I doubt there's any queue packets.

**Comment by chemicalcrux** [comment]
Does it work with a headless user that's hosting the world? That would let you get a second "user" to trigger the bug with.

**Comment by Frooxius** [comment]
I'm using two machines with regular users to replicate. Is this something that happens only on headless servers? That's not something I tested.

**Comment by Hayden-da-Serg** [comment]
I haven't tested on headless specifically, in all of my testing I have myself being the host and a remote user, in all cases of one user anchoring another it's offset, no matter if it's host to remote, remote to host, or remote to remote, as noted earlier the offsets appear to be worse the higher the latency is.

**Comment by chemicalcrux** [comment]
This is reproducing for me (on the current build) with a headless client hosting the world. It's running on the same machine, so latency should not be relevant here.

When I make the headless user trigger the impulse, I wind up with strange positions and rotations. When I trigger it myself, it behaves as expected.

I tried rearranging the slots around (user and anchor under the same parent, user and anchor under different parents), and did not observe a difference.

**Comment by Hayden-da-Serg** [comment]
Any updates on this?

**Comment by Frooxius** [comment]
We'll post updates when we have any. I still can't replicate it on my end, it works perfectly every time I try. I still can't replicate this on my end, so like I mentioned above I'll have to push an instrumented build for you test and send me the logs back.

If anyone else can find a good way to reliably replicate this that can help speed up the process.

**Comment by Electronus** [comment]
So I got this to happen to kier and I, it wasn't a clean test, there were other uses in the world, but the ping to kier form me was reported a 0ms with spikes up to 3ms.  (we are in the same room so this is normal). 

I just used the test set up hayden posted.

**Comment by Frooxius** [comment]
What were your testing conditions for that? I used similar setup on local network and it always anchors the user perfectly.

**Comment by Electronus** [comment]
It was the Logix Hayden has above. Kier was hosting the world and I was connected normally however NEOS decides to do that with an invite when on the same network. (but world isn't set to LAN)

**Comment by Electronus** [comment]
If your looking for different information im afraid your going to have to ask directly, because I dont know what exactly you mean by "set up".

**Comment by chemicalcrux** [comment]
I've tried this with a number of different avatars (including a plain box), and they have no apparent effect on the bug. Every avatar I tried wound up putting me at weird positions and rotations when anchored by another user.

I am also using Hayden's setup. It works reliably for me in a world without anything else in it.

Here's a video of what I'm experiencing. I turned the delay from 5 seconds to 1 second to make it faster to demonstrate.

The first three anchorings are being performed by the headless user that's hosting the session. The last thre anchorings are being performed by myself.

https://user-images.githubusercontent.com/8015368/107861020-0908c080-6e11-11eb-8307-70e29d5b2d09.mp4

**Comment by Electronus** [comment]
Just did more testing with Kier, first test was me, Kier and Ukilop in a new empty world. I spawned the test setup Hayden made, and it acted as I expected, if Kier fired the impulse to anchor me then it was majorly offset in seemingly random rotations and positions. (Kier noted they looked the same distance offset, but I cant confirm). I was offset on the first anchor and even more so on the second. 

Uki left the world and we repeated the test with the same results. 

When I was the user to fire the impulse it worked as it should with no offsets on position or rotation. 

We tested with Kier having the impulse coming form me and it worked as expected, with no offsets. 

Host being present makes no difference. 

The user who anchors the other user sees the anchored user in the correct position very briefly (one frame?) then they end up offset.

**Comment by Hayden-da-Serg** [comment]
Is there any more information needed for testing or a replication case?

**Comment by WolvesAndOwls** [comment]
I had the same problem, and I was able to come to a conclusion. The offset happens when another user is put into an anchor. To fix this, every user should be assigned to their anchor by a fire while true on their client, never on someone else’s. When player 1 tells player 2 to get into a seat, player 1 sends the old location, and player 2 is offset.

**Comment by Frooxius** [comment]
Can you please check if this issues still persists in 2021.3.5.176? I have made some changes in this build to how the transform stream is handled.

**Comment by Hayden-da-Serg** [comment]
Nope, still offset.

**Comment by Hayden-da-Serg** [comment]
I'm really curious what's different about your replication case from mine that's not allowing you to reproduce the issue on your end.

**Comment by Frooxius** [comment]
I don't know, that's what we need to find out. The only differences I could think of were the ones I mentioned above, but you said that it still occurs with those on your end too.

If you can send me the replication case in a world that might help isolate any potential differences more. I spawned the one you sent in one of my testing worlds.

**Comment by Hayden-da-Serg** [comment]
With some testing, I found that the issue can only be replicated if the anchors are moved after their spawned, if they are not moved at all, then everything functions fine, thankfully on the test item provided both the anchors are on sliders.

**Comment by Hayden-da-Serg** [comment]
Just in case, I made a world here; neosrec:///U-Hayden/R-a30cae7f-df77-46ba-a201-1be106e98694
This has a very simple setup with an anchor that's on a Wiggler so it's constantly being transformed.

**Comment by Daniel-Luke-Taylor** [comment]
Can confirm this is still an issue in the current public build (2021.5.20.1063), replicated with Electronus#5305 while testing to see if a similar issue was related last night. ( #2310 )

**Comment by shiftyscales** [comment]
@Frooxius - I've created another replication case for this issue in this world: http://cloudx.azurewebsites.net/open/world/U-Shifty/R-85b7a445-2419-4b62-9256-86d2a93e8886

It explicitly requires a second client to test it (local or remote). It is not possible to replicate the issue by having a user anchor themselves (local or remote) anchor themselves if they are the one pressing the impulse.

- Have a non-host user press the pulse to anchor the host, and note they are offset from the anchor compared to when they anchor themselves

As noted, the issue only occurs when an impulse is sent from a user that is different to the one being anchored.

The anchored user is placed in front of the position of the anchor is moving towards.

The user is also offset proportionally to the speed of the panner. A slower panner will offset the user less than one moving extremely quickly.

This suggests the user is being anchored in the position the anchor will be on the next frame/this is an update order issue.

This issue also occurs with two clients run locally on the same PC eliminating the possibility of latency being a factor because the reported latency is 0 for both clients when testing it locally.

Relative user position on anchor when the panner speed is set to 1:
![image](https://user-images.githubusercontent.com/54213390/122292246-9e44c000-ceaa-11eb-9c3b-ea0fc2436194.png)

Relative user position on anchor when the panner speed is set to 100000:
![image](https://user-images.githubusercontent.com/54213390/122292388-cb916e00-ceaa-11eb-942a-68735af22c67.png)

**Comment by Bontebok** [comment]
I know this issue is almost 10 months old but I wanted to comment that it is still occurring. For Creator Jam #128 "Zoop" we used anchoring a lot and this issue came up early on, however we found a sort-of workaround that involved disabling the Require option for Hips in the Anchor Body Nodes list. This prevents the "stretching" issue when anchoring using Logix (At least it did in our case). The user still is anchored rather correctly even without it checked, however your mileage may vary.

![Screenshot from 2021-11-23 17-43-37](https://user-images.githubusercontent.com/23562523/143141096-7840a1e7-dc56-4f51-8f0b-288b280ae416.png)
